apiVersion: v1
kind: Service
metadata:
  name: django-notes-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app: django-notes
  ports:
    - protocol: TCP
      port: 5000  # Port exposed by the service externally (outside the cluster)
      targetPort: 5000  # Port your application listens on inside the pods
  type: LoadBalancer
